name: CI Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "CI workflow detected at $(date)" 
